### ISSUE TITLE
full example

### ISSUE THREAD

**Issue by zhanghongjie101** [bparr/gpu-experience-replay#1]
Can you give us a full example? I do not know how to use it, thx.

**Comment by bparr** [comment]
Good question. Here's the branch with the code that the report is based on (it's in a repo from the Deep RL class project also mentioned in the report):

Creating the model (what example.py is based on): https://github.com/bparr/melee-ai/blob/shortRun/dqn_atari.py#L113
sess.run line (with feed_dict arg no longer needed): https://github.com/bparr/melee-ai/blob/shortRun/deeprl_hw2/dqn.py#L188
